#ifndef TRANSITIONDEFINITIONS_H
#define TRANSITIONDEFINITIONS_H

// First has value 0, second is 1,so on...
enum transition_animation {
    TRANSITION_PUSH_LEFT, 
    TRANSITION_PUSH_RIGHT,
    TRANSITION_PUSH_UP,
    TRANSITION_PUSH_DOWN,
    TRANSITION_WIPE_LEFT,
    TRANSITION_WIPE_RIGHT
};


#endif // TRANSITIONDEFINITIONS_H